
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuomjtvocloviqxtqvuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1b21qdHZvY2xvdmlxeHRxdnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDg4NDAsImV4cCI6MjA1ODcyNDg0MH0.QKbFIkDwc6fk6vrTfoILQm_Q2Ivuyi95MK00UW2Qk34";

// Create the Supabase client with realtime functionality enabled
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY, 
  {
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    },
    db: {
      schema: 'public'
    },
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: false // Prevent URL hash parsing to avoid navigation issues
    }
  }
);

// Export a helper function to log errors in a structured way
export const logSupabaseError = (error: any, context: string) => {
  console.error(`Supabase error in ${context}:`, error);
  if (error?.message) {
    console.error('Message:', error.message);
  }
  if (error?.details) {
    console.error('Details:', error.details);
  }
  return error;
};
